version: 2.1

slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - run: docker pull cimg/base:stable
    - slack/notify:
        template: basic_fail_1
        event: fail

orbs:
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.0

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      # - heroku/deploy-via-git
      - run: echo "Sending status"
      # - slack/notify:
      #     event: fail
      #     template: basic_fail_1
      - slack/notify:
          # event: pass
          template: success_tagged_deploy_1

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          <<: *slack-fail-post-step
      - notify:
          requires:
            - heroku/deploy-via-git