version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
# workflows:
#   heroku_deploy:
#     jobs:
#       - heroku/deploy-via-git
#   send-notification:
#     jobs:
#       - notify:
#           context: slack-secrets

workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets