//resgiter
POST http://localhost:8000/api/authentication/register
Content-Type: application/json

{
    "account_username": "duy",    
    "account_password": "123",
    "account_role" : "teacher"
}
###
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "account_username": "duy",
    "account_password": "12"
}