//resgiter
POST http://localhost:8000/api/authentication/register
Content-Type: application/json

{
    "account_username": "duy4",    
    "account_password": "123",
    "account_role" : "Principal"
}
###
POST http://localhost:8000/api/authentication/login
Content-Type: application/json

{
    "account_username": "headquater123",
    "account_password": "123456"
}