###
//create principal
POST http://localhost:8000/api/admin/principal
Content-Type: application/json

{
    "account_username":"testhieutruong",
    "account_password": "123456",
    "person_fullname":"Le Duy manh",
    "person_dateofbirth":"2021-12-01T17:00:00.000+00:00",
    "person_email":"lmsd@g.com",
    "person_gender": true,
    "person_phonenumber":"083404612345",
    "person_address":"50 Trung Nu Vuongggg",
    "person_image":"testing"
}

###
//get principle
GET http://localhost:8000/api/admin/principal
Content-Type: application/json

###
//update principle
PUT http://localhost:8000/api/admin/principal/6348c837e62d3c8b2f862293
Content-Type: application/json

{
    "account_username":"testing",
    "account_password": "654321",
    "person_fullname":"Duy testing",
    "person_dateofbirth":"2014-11-05T17:00:00.000+00:00",
    "person_email":"lmd@yahoo.com",
    "person_gender": false,
    "person_phonenumber":"0834012345",
    "person_address":"50 Trung",
    "person_image":"aaaa"
}

###
//delete principle
DELETE http://localhost:8000/api/admin/principal/6347e9e1d8cc7d034675b364